name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: dummy

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        working-directory: infrastructure/
        run: |
          node -v
          npm ci
      - name: Build
        working-directory: infrastructure/
        run: npm run build
      - name: Lint
        working-directory: infrastructure/
        run: npm run lint
